
#黄金页面的黄金元素
GOLD_LIST:
  - { GOLD_PAGE: 闲鱼-闲置换钱,GOLD_ITEMS: [我的] }
  - { GOLD_PAGE: 阿里众包,GOLD_ITEMS: [我的] }
GENERAL:
  #截屏数量
  SCREENSHOT_COUNT: 500
  #Crash时截图显示步骤数量
  CRASH_PIC_COUNT: 10
  #遍历深度
  MAX_DEPTH: 800
  #点击次数
  MAX_CLICK_COUNT: 100000
  #TIME
  DEFAULT_WAIT_SEC: 10
  #查找元素的间隔时间
  DEFAULT_POLLING_INTERVAL_SEC: 5
  #是否忽略Crash,设为true时,crash后会重启app然后继续遍历
  IGNORE_CRASH: false
  #是否屏蔽DOM树在Log中的显示
  DISABLE_DOM_DISPLAY: false
  #遍历的过程中进行向上划动操作  ！！！此项会加长遍历时间！！！
  ENABLE_VERTICAL_SWIPE: false
  #运行时间限制(分钟)
  CRAWLER_RUNNING_TIME: 1800
  #忽略底部元素Bounds值
  REMOVE_BOTTOM_BOUND: true
  #灰名页面遍历的最大次数（两个页面进入循环）
  gray_activity_max_traverse: 2
  #灰名页面遍历自己遍历最大次数（单个页面进入死循环了）
  gray_activity_max_traverse_itself: 2
  can_scrolled_page_xpath: '(.//*[@scrollable="true"])'


#一些默认值
DEFAULT_VALUE:
  #Appium server IP， 0.0.0.0代表Server在本地
  APPIUM_SERVER_IP: 0.0.0.0
  #Appium端口
  PORT: 4723



#以下的内容很关键，而且需要根据不同的APP定制
CRITICAL_ELEMENT:
  #Android包名和启动的Activity
  #微信小程序用以下面注释的包名
  #ANDROID_PACKAGE: com.tencent.mm
  #ANDROID_MAIN_ACTIVITY: com.tencent.mm.ui.LauncherUI
  ANDROID_PACKAGE: com.taobao.taobao
  ANDROID_MAIN_ACTIVITY: com.taobao.tao.welcome.Welcome



#构建XPATH需要的一些内容
  #UI底部TabBar
#ANDROID_BOTTOM_TAB_BAR_ID: com.huxiu:id/footer_bar


  #注意值要加引号'' ( (string-length(@text)<10  and string-length(@text)>1) or contains(@text,"允许")  or (string-length(@content-desc)<10 and string-length(@content-desc)>1)) '
  ANDROID_CLICK_XPATH_HEADER: ' (string-length(@content-desc)<6 and string-length(@content-desc)>1) '

LIST:

  #当遇到下列文字时会触发手机BackPress  黄金名单activity或者页面title，如果匹配到黄金名单了，则直接上传source，截图，并返回,且不处理子nodes
  BACK_KEY_TRIGGER_LIST:
  - 我的账单
  - 订单详情

  CAN_SCROOLED_PAGES:
  - com.taobao.tao.mytaobao.MyTaoBaoActivity
  - com.taobao.mytaobao.allapp.AllAppsActivity
  can_scrolled_page_length: 2
  #待输入文本的控制类型
  INPUT_CLASS_LIST:
  - android.widget.TextView
  - XCUIElementTypeTextField
  - XCUIElementTypeSecureTextField

  #待输入的文本（随机选中后选列表中的一个）
  INPUT_TEXT_LIST:
  - '123'
  - 'ABC'

  #当发现App跳转到一下app时 会触发back键
  PRESS_BACK_KEY_PACKAGE_LIST:
  - 高德地图
  - com.autonavi.minimap
  - com.android.settings

  #除了APP本身的包名外 根据以下包名判断是否跳出了APP,当app跳转到以下app时被认为是合法，会继续遍历操作
  ANDROID_VALID_PACKAGE_LIST:
  #- com.miui.securitycenter
  #- com.android.server.telecom
  #- com.lbe.security.miui
  #- gallery
  #- packageinstaller


  #白名单，遇到包含以下文本的控件，会多次点击（默认所有控件只点一次）
  ITEM_WHITE_LIST:
  - 确定
  - 允许
  - 退出
  - 取消
  - 已解决

  #不点击包含以下文本的控件
  ITEM_BLACKLIST:
  - 客服
  - 电话
  - 不允许
  - 拒绝
  - 拍照
  - 禁止
  - 呼叫
  - 低电量模式
  - 关闭
  - 收藏夹
  - 关注店铺
  - 足迹
  - 红包卡券
  - 天天红包赛
  - 答题红包塞
  - 添加卡片
  - com.taobao.taobao:id/btn_add_card
  - 首页
  - 微淘
  - 消息
  - 购物车
  - 我的淘宝
  - 客服小蜜
  - 反馈
  - 管理
  - 主题
  - 换肤
  - 评价
  - 宝卡
  - 野生小伙伴
  - 领券中心
  - 刷新
  - 分享
  - 更多
  - 抢购
  - 领取
  - 会员
  - 打赏明细
  - 发票
  - 拍卖
  - 我的问答
  - 我的话题
  - 我的评价
  - 公益
  - 每日打卡
  - 大众评审
  - 分享有赏
  - 淘日历
  - 会员码
  - 实人通行证
  - 天猫精灵
  - 安全中心
  - 天猫路由
  - 拍立淘
  - 资产变现
  - 预约有礼
  - 咸鱼回收
  - 天猫无忧
  - 我要卖车
  - 我的爱车
  - 彩票助手
  - 租房
  - 领金币
  - 我要定制
  - 优先试用
  - 全球播报
  - 海淘笔记
  - 进口优选
  - 淘宝租赁
  - 10元
  - 淘必中
  - 淘宝必选
  - 课堂
  - 淘乡甜
  - 演出赛事
  - 医药健康
  - 我的快递
  - 我的通信
  - 高薪工作
  - 我的超市
  - 我的学习
  - 出境超市
  - 邻里成
  - 飞猪酒店
  - 目的地
  - 机票火车票
  - 定制旅行
  - 特惠门票
  - 港澳台
  - 上门
  - 数码
  - 家居
  - 更多服务
  - 阿里云
  - 淘票票
  - 口碑
  - 体育
  - 优酷
  - 开店
  - 保卡
  - 交易猫
  - 饿了么
  - 投诉
  - 元
  - 斤
  - 卖
  - 买
  - 个
  - 只
  - 颗
  - ¥
  - 送
  - 箱
  - 瓶


  #黑名单activity或者页面title
  black_pages:
  - 反馈
  - 举报
  - 家庭主页
  - 我的通信





    #手机状态栏
  - XCUIElementTypeStatusBar
  #键盘
  - XCUIElementTypeKeyboard



  ANDROID_EXCLUDE_TYPE:
  #- android.widget.FrameLayout
  - android.widget.ImageButton
  - android.widget.Button

  #解释待续
  NODE_NAME_EXCLUDE_LIST:
  - selected
  - instance
  - checked
  - naf
  - content

  #解释待续
  STRUCTURE_NODE_NAME_EXCLUDE_LIST:
  #- value
  - name

  #Android
  - text



#设备udid 对应的设备名称
#d6744554:
#  DEVICE_NAME: XiaoMi4


